### ISSUE TITLE
High failure rates for Team Open Science Grid

### ISSUE THREAD

**Issue by jchodera** [lukasheinrich/folding-at-home-docker#14]
@lukasheinrich: I'm not sure if you're the appropriate contact, but we ([the Folding@home Consortium](https://foldingathome.org/about/the-foldinghome-consortium/)) have been seeing persistent high failure rates for Folding@home clients run by [Team Open Science Grid](https://stats.foldingathome.org/team/258507). For example, there are many instances in the stats database where a client run by Team Open Science Grid fails repeatedly before another client completes the work unit:
![image](https://user-images.githubusercontent.com/3656088/99035135-ce526c00-2533-11eb-9bf0-2ef32df55825.png)

We suspect something is misconfigured with whoever is running these FAH clients, and are looking to get in touch with them. Do you know if the FAH client docker container you have configured is currently in use?

Note that the [official Folding@home client Docker image](https://github.com/FoldingAtHome/containers) is actively maintained both by Folding@home and NVIDIA devs, and we can ensure that it is configured properly.

**Comment by lukasheinrich** [comment]
hi @jchodera - hm I'm mostly involved in https://stats.foldingathome.org/team/38188 but we have a few connections to OSG. Maybe @pelmer @afortiorama know who is running OSG FAH operations (i'll also distribute this across some internal channels).

**Comment by lukasheinrich** [comment]
maybe @bbockelm or @brianhlin also know who to contact

**Comment by lukasheinrich** [comment]
just an update @djw8605 is working on this right now

**Comment by jchodera** [comment]
Thanks so much @lukasheinrich!

**Comment by djw8605** [comment]
@jchodera, we can coordinate on the other issue you opened https://github.com/djw8605/covid-submit/issues/1

**Comment by jchodera** [comment]
Thanks!
